### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Sadriica** [Sadriica/IMH#1]

**Comment by ismc0** [comment]
Condición de aceptación: 
La landing page deberá de tener toda la información acerca de la plataforma e iniciación del usuario para que pueda ingresar a seguir con su progreso. Esto incluye el contacto, "acerca de nosotros", la información del progreso del usuario y los proyectos en los que está involucrado, y las sugerencias de futuros proyectos a los que podría aspirar.
