### ISSUE TITLE
Registration Form

### ISSUE THREAD

**Issue by Sadriica** [Sadriica/IMH#4]

**Comment by ismc0** [comment]
Condición de aceptación: 
El form que deberán de llenar los usuarios para poder hacer uso de la plataforma. esto incluye campos como el nombre de la compañía a la que pertenecen, nombre registrado bajo la compañía, email, persona encargada, rol dentro de la compañía, y una clave de sólo 1 vez. Dicha clave será distribuida por la persona encargada una vez se verifique la identidad de la persona.
